// <auto-generated />
using System;
using BCKGRND.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BCKGRND.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20221206203754_locationTest3")]
    partial class locationTest3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BCKGRND.Models.Location", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarChar(200)");

                    b.Property<float>("Latitude")
                        .HasColumnType("FLOAT(9, 7)");

                    b.Property<float>("Longtitude")
                        .HasColumnType("FLOAT(10, 7)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarChar(50)");

                    b.HasKey("ID");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("BCKGRND.Models.Photo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte[]>("Image")
                        .HasColumnType("MEDIUMBLOB");

                    b.Property<int?>("LocationID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("LocationID");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("BCKGRND.Models.Tag", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarChar(30)");

                    b.HasKey("ID");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("BCKGRND.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarChar(30)");

                    b.Property<string>("UserMail")
                        .HasColumnType("nvarChar(100)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarChar(30)");

                    b.Property<string>("UserPass")
                        .HasColumnType("nvarChar(100)");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LocationTag", b =>
                {
                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<int>("TagsID")
                        .HasColumnType("int");

                    b.HasKey("LocationID", "TagsID");

                    b.HasIndex("TagsID");

                    b.ToTable("LocationTag");
                });

            modelBuilder.Entity("BCKGRND.Models.Photo", b =>
                {
                    b.HasOne("BCKGRND.Models.Location", "Location")
                        .WithMany("Photos")
                        .HasForeignKey("LocationID");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("LocationTag", b =>
                {
                    b.HasOne("BCKGRND.Models.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BCKGRND.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BCKGRND.Models.Location", b =>
                {
                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
